open_system(new_system("NHLimiter"))
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in0)
set_param("NHLimiter/in0", "position", [0,0,40,40])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in1)
set_param("NHLimiter/in1", "position", [0,40,40,80])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in2)
set_param("NHLimiter/in2", "position", [0,80,40,120])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in3)
set_param("NHLimiter/in3", "position", [0,120,40,160])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in4)
set_param("NHLimiter/in4", "position", [0,160,40,200])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in5)
set_param("NHLimiter/in5", "position", [0,200,40,240])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in6)
set_param("NHLimiter/in6", "position", [0,240,40,280])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in7)
set_param("NHLimiter/in7", "position", [0,280,40,320])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in8)
set_param("NHLimiter/in8", "position", [0,320,40,360])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in9)
set_param("NHLimiter/in9", "position", [0,360,40,400])
add_block("simulink/Commonly Used Blocks/In1", "NHLimiter/in10)
set_param("NHLimiter/in10", "position", [0,400,40,440])
